-- MySQL Script generated by MySQL Workbench
-- Wed Nov 25 22:01:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
                                             `id` VARCHAR(50) NOT NULL,
                                             `name` VARCHAR(45) NULL,
                                             `phone` VARCHAR(45) NULL,
                                             `address_info` VARCHAR(300) NULL,
                                             PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
                                                `id` VARCHAR(50) NOT NULL,
                                                `name` VARCHAR(45) NULL,
                                                `price` DECIMAL(12) NULL,
                                                `inventory` INT NULL,
                                                `unit` VARCHAR(45) NULL,
                                                PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_product` (
                                                      `order_id` VARCHAR(45) NOT NULL,
                                                      `id` VARCHAR(50) NOT NULL,
                                                      `name` VARCHAR(45) NULL,
                                                      `price` DECIMAL(12) NULL,
                                                      `unit` VARCHAR(45) NULL,
                                                      PRIMARY KEY (`order_id`, `id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_item` (
                                                   `id` VARCHAR(50) NOT NULL,
                                                   `order_id` VARCHAR(50) NULL,
                                                   `price` DECIMAL(12) NULL,
                                                   `create_time` DATETIME NULL,
                                                   `update_time` DATETIME NULL,
                                                   `product_id` VARCHAR(50) NULL,
                                                   PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
                                               `id` VARCHAR(50) NOT NULL,
                                               `create_time` DATETIME NULL,
                                               `update_time` DATETIME NULL,
                                               `status` VARCHAR(45) NULL,
                                               `address_info` VARCHAR(300) NULL,
                                               `pay` DECIMAL(12) NULL,
                                               PRIMARY KEY (`id`))
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
